ALTER TABLE "Note" ADD COLUMN "title" TEXT NOT NULL DEFAULT 'Note';
ALTER TABLE "Note" ADD COLUMN "headerBg" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Note" ADD COLUMN "noteBg" TEXT NOT NULL DEFAULT '';
